### ISSUE TITLE
<footer id="foot"> does not honor [hidden]

### ISSUE THREAD

**Issue by explorigin** [rackerlabs/helix-ui#440]
## Describe the Bug
`<footer id="foot" hidden>` does not hide the element.

## Steps to Reproduce

1. Use the above tag in an example layout page

## Expected behavior
It should not be visible

## Screenshots
<img width="944" alt="screen shot 2019-02-01 at 2 39 30 pm" src="https://user-images.githubusercontent.com/697818/52148517-92386a80-262f-11e9-9fcc-32cbd079c18c.png">

## Environment
Please complete the following information:
Chrome 71 on Mac

**Comment by explorigin** [comment]
Fixed by:
```css
    #foot[hidden] {
      display: none;
    }
```

**Comment by CITguy** [comment]
Any element with the `hidden` attribute should not be rendered. Therefore, the `[hidden]` attribute behaves more like a helper than a reset. 

Using `#foot[hidden]` only fixes the issue for the `#foot` element, but it doesn't apply to other potential scenarios.  A more appropriate fix would be:

```less
[hidden] {
  display: none !important;
}
```
